getConfig=\
SELECT \
    "value" \
FROM \
    "config" \
WHERE \
    "id" = ?

addConfig=\
INSERT INTO \
    "config" ("id", "value") \
VALUES \
    (?, ?)

updateConfig=\
UPDATE \
    "config" \
SET \
    "value" = ? \
WHERE \
    "id" = ?

removeConfig=\
DELETE FROM \
    "config" \
WHERE \
    "id" = ?
