:_mod-docs-content-type: PROCEDURE

[id="installing-ca-with-existing-keys-in-hsm"]
= Installing CA with existing keys in HSM 

Follow this process to install a CA subsystem with the system keys, CSRs, and certificates from an existing CA where the keys are stored on a HSM.

To avoid conflicts with the existing CA subsystem, the new CA subsystem uses new SSL server and subsystem certificates, so they will not be included in the installation process.

Prior to installation, please ensure that the xref:../others/installation-prerequisites.adoc[Installation Prerequisites] are configured.

== Exporting existing system certificates and CSRs

Export the system certificates and the CSR from the existing CA with the following commands:

[literal,subs="+quotes,verbatim"]
....
$ pki-server cert-export \
    --cert-file ca_signing.crt \
    --csr-file ca_signing.csr \
    ca_signing
$ pki-server cert-export \
    --cert-file ca_ocsp_signing.crt \
    --csr-file ca_ocsp_signing.csr \
    ca_ocsp_signing
$ pki-server cert-export \
    --cert-file ca_audit_signing.crt \
    --csr-file ca_audit_signing.csr \
    ca_audit_signing
....

== Starting a CA subsystem

Prepare a file, for example `ca.cfg`, that contains the deployment configuration.

A sample deployment configuration is available at xref:../../../base/server/examples/installation/ca.cfg[/usr/share/pki/server/examples/installation/ca.cfg].

Specify the HSM configuration with the following parameters:

[literal,subs="+quotes,verbatim"]
....
[DEFAULT]
pki_hsm_enable=True
pki_hsm_libfile=/usr/lib64/pkcs11/libsofthsm2.so
pki_hsm_modulename=softhsm
pki_token_name=HSM
pki_token_password=Secret.123

[CA]
pki_ca_signing_nickname=ca_signing
pki_ocsp_signing_nickname=ca_ocsp_signing
pki_audit_signing_nickname=ca_audit_signing
pki_sslserver_nickname=sslserver/pki.example.com
pki_subsystem_nickname=subsystem/pki.example.com
....

Specify the existing certificates and the CSRs with the following parameters:

[literal,subs="+quotes,verbatim"]
....
pki_ca_signing_token=HSM
pki_ca_signing_cert_path=ca_signing.crt
pki_ca_signing_csr_path=ca_signing.csr
pki_ocsp_signing_token=HSM
pki_ocsp_signing_cert_path=ca_ocsp_signing.crt
pki_ocsp_signing_csr_path=ca_ocsp_signing.csr
pki_audit_signing_nickname=HSM
pki_audit_signing_cert_path=ca_audit_signing.crt
pki_audit_signing_csr_path=ca_audit_signing.csr
....

These parameters can be added into the file or specified with the `-D` option below:

Execute the following command:

[literal,subs="+quotes,verbatim"]
....
$ pkispawn \
    -f ca.cfg \
    -s CA \
    -D pki_ca_signing_token=HSM \
    -D pki_ca_signing_cert_path=ca_signing.crt \
    -D pki_ca_signing_csr_path=ca_signing.csr \
    -D pki_ocsp_signing_token=HSM \
    -D pki_ocsp_signing_cert_path=ca_ocsp_signing.crt \
    -D pki_ocsp_signing_csr_path=ca_ocsp_signing.csr \
    -D pki_audit_signing_nickname=HSM \
    -D pki_audit_signing_cert_path=ca_audit_signing.crt \
    -D pki_audit_signing_csr_path=ca_audit_signing.csr
....

It installs a CA subsystem in a Tomcat instance (default is pki-tomcat) and creates the following NSS databases:

* server NSS database: /var/lib/pki/pki-tomcat/conf/alias

* admin NSS database: ~/.dogtag/pki-tomcat/ca/alias

Since there are no CSR path parameters specified, it does not generate CA system and admin keys.

== Verifying system certificates 

. Verify that the internal token contains the following certificates:
+
[literal,subs="+quotes,verbatim"]
....
$ certutil -L -d /var/lib/pki/pki-tomcat/conf/alias

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

ca_signing                                                   CT,C,C
ca_audit_signing                                             ,,P
....

. Verify that the HSM contains the following certificates:
+
[literal,subs="+quotes,verbatim"]
....
$ certutil -L -d /var/lib/pki/pki-tomcat/conf/alias -h HSM -f HSM.pwd

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

HSM:ca_signing                                               CTu,Cu,Cu
HSM:ca_ocsp_signing                                          u,u,u
HSM:subsystem/pki.example.com                                u,u,u
HSM:ca_audit_signing                                         u,u,Pu
HSM:sslserver/pki.example.com                                u,u,u
....

== Verifying the admin certificate 

. Import the CA signing certificate:
+
[literal,subs="+quotes,verbatim"]
....
$ pki nss-cert-import --cert ca_signing.crt --trust CT,C,C ca_signing
....

. Import the admin certificate and key into the client NSS database (by default ~/.dogtag/nssdb) with the following command:
+
[literal,subs="+quotes,verbatim"]
....
$ pki -c Secret.123 pkcs12-import \
    --pkcs12 ~/.dogtag/pki-tomcat/ca_admin_cert.p12 \
    --pkcs12-password Secret.123
....

. Verify that the admin certificate can be used to access the CA subsystem by executing the following command:
+
[literal,subs="+quotes,verbatim"]
....
$ pki -c Secret.123 -n caadmin ca-user-show caadmin
--------------
User "caadmin"
--------------
  User ID: caadmin
  Full name: caadmin
  Email: caadmin@example.com
  Type: adminType
  State: 1
....
