name: ACME Tests

on: [push, pull_request]

jobs:
  build:
    name: Waiting for build
    uses: ./.github/workflows/wait-for-build.yml
    secrets: inherit

  acme-basic-test:
    name: Basic ACME
    needs: build
    uses: ./.github/workflows/acme-basic-test.yml

  acme-separate-test:
    name: ACME on separate instance
    needs: build
    uses: ./.github/workflows/acme-separate-test.yml

  acme-existing-nssdb-test:
    name: ACME with existing NSS database
    needs: build
    uses: ./.github/workflows/acme-existing-nssdb-test.yml

  acme-switchover-test:
    name: ACME server switchover
    needs: build
    uses: ./.github/workflows/acme-switchover-test.yml

  acme-container-basic-test:
    name: Basic ACME container
    needs: build
    uses: ./.github/workflows/acme-container-basic-test.yml

  acme-container-ca-test:
    name: ACME container with CA
    needs: build
    uses: ./.github/workflows/acme-container-ca-test.yml

  acme-postgresql-test:
    name: ACME with postgresql back-end
    needs: build
    uses: ./.github/workflows/acme-postgresql-test.yml

  acme-clone-test:
    name: ACME clone
    needs: build
    uses: ./.github/workflows/acme-clone-test.yml

  publish:
    if: github.event_name == 'push' && github.ref_name == 'master'
    name: Publishing ACME images
    needs: build
    runs-on: ubuntu-latest
    env:
      NAMESPACE: ${{ vars.REGISTRY_NAMESPACE || github.repository_owner }}
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: vars.REGISTRY == 'ghcr.io'

      - name: Log in to other container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        if: vars.REGISTRY != 'ghcr.io'

      - name: Retrieve ACME images
        uses: actions/cache@v5
        with:
          key: pki-images-${{ github.sha }}
          path: pki-images.tar

      - name: Load ACME images
        run: docker load --input pki-images.tar

      - name: Publish pki-acme image
        run: |
          docker tag pki-acme ${{ vars.REGISTRY }}/$NAMESPACE/pki-acme:latest
          docker push ${{ vars.REGISTRY }}/$NAMESPACE/pki-acme:latest
