name: CA API
# This test will perform the following operations:
# - install CA
# - check pki info with default API
# - check pki info with API v1
# - check pki ca-cert-find with default API
# - check pki ca-cert-find with API v1
# - check pki ca-user-show with default API
# - check pki ca-user-show with API v1
# - check pki ca-cert-request-find with default API
# - check pki ca-cert-request-find with API v1
# - check pki ca-cert-issue with default API
# - check pki ca-cert-issue with API v1
# - check pki ca-sd-join and ca-sd-leave with default API

on: workflow_call

env:
  DS_IMAGE: ${{ vars.DS_IMAGE || 'quay.io/389ds/dirsrv' }}

jobs:
  # docs/installation/ca/Installing_CA.md
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Retrieve PKI images
        uses: actions/cache@v4
        with:
          key: pki-images-${{ github.sha }}
          path: pki-images.tar

      - name: Load PKI images
        run: docker load --input pki-images.tar

      - name: Create network
        run: docker network create example

      - name: Set up DS container
        run: |
          tests/bin/ds-create.sh \
              --image=${{ env.DS_IMAGE }} \
              --hostname=ds.example.com \
              --network=example \
              --network-alias=ds.example.com \
              --password=Secret.123 \
              ds

      - name: Set up PKI container
        run: |
          tests/bin/runner-init.sh \
              --hostname=pki.example.com \
              --network=example \
              --network-alias=pki.example.com \
              pki

          docker exec pki dnf install -y xmlstarlet

      - name: Set up client container
        run: |
          tests/bin/runner-init.sh \
              --hostname=client.example.com \
              --network=example \
              --network-alias=client.example.com \
              client

      - name: Install CA
        run: |
          docker exec pki pkispawn \
              -f /usr/share/pki/server/examples/installation/ca.cfg \
              -s CA \
              -D pki_ds_url=ldap://ds.example.com:3389 \
              -D pki_audit_signing_nickname= \
              -v

      - name: Disable access log buffer
        run: |
          docker exec pki xmlstarlet edit --inplace \
              -u "//Valve[@className='org.apache.catalina.valves.AccessLogValve']/@buffered" \
              -v "false" \
              -i "//Valve[@className='org.apache.catalina.valves.AccessLogValve' and not(@buffered)]" \
              -t attr \
              -n "buffered" \
              -v "false" \
              /etc/pki/pki-tomcat/server.xml

      - name: Configure RESTEasy logging
        run: |
          docker exec -i pki tee /var/lib/pki/pki-tomcat/conf/ca/logging.properties << EOF
          org.jboss.resteasy.level = INFO
          EOF

          docker exec pki chown pkiuser:pkiuser /var/lib/pki/pki-tomcat/conf/ca/logging.properties

      - name: Restart PKI server
        if: false
        run: |
          docker exec pki pki-server restart --wait

      - name: Install CA signing cert
        run: |
          docker exec pki pki-server cert-export \
              --cert-file $SHARED/ca_signing.crt \
              ca_signing

          docker exec client pki nss-cert-import \
              --cert $SHARED/ca_signing.crt \
              --trust CT,C,C \
              ca_signing

      - name: Install subsystem cert and key
        run: |
          docker exec pki pki-server cert-export \
              --pkcs12-file $SHARED/subsystem.p12 \
              --pkcs12-password Secret.123 \
              subsystem

          docker exec client pki pkcs12-import \
              --pkcs12 $SHARED/subsystem.p12 \
              --password Secret.123

      - name: Install CA admin cert and key
        run: |
          docker cp pki:/root/.dogtag/pki-tomcat/ca_admin_cert.p12 .

          docker exec client pki pkcs12-import \
              --pkcs12 $SHARED/ca_admin_cert.p12 \
              --password Secret.123

      - name: Check pki info with default API
        if: false
        run: |
          for i in {1..1}; do
              docker exec client \
                  -U https://pki.example.com:8443 \
                  pki info
          done

          # check HTTP methods, paths, protocols, status, and authenticated users
          docker exec pki find /var/log/pki/pki-tomcat \
              -name "localhost_access_log.*" \
              -exec cat {} \; \
              | tail -2 \
              | sed -e 's/^.* .* \(.*\) \[.*\] "\(.*\)" \(.*\) .*$/\2 \3 \1/' \
              | tee output

          # normalize output
          sed \
              -e 's/^\(GET \/ca\/ocsp\/\)[^ ]* \(.*\)$/\1XXXXX \2/' \
              output > actual

          rm -f expected

          for i in {1..1}; do
              cat >> expected << EOF
          GET /ca/ocsp/XXXXX HTTP/1.0 200 -
          GET /pki/v2/info HTTP/1.1 200 -
          EOF
          done

          diff expected actual || true

      - name: Check pki info with API v1
        if: false
        run: |
          docker exec client pki \
              -U https://pki.example.com:8443 \
              --api v1 \
              info

          # check HTTP methods, paths, protocols, status, and authenticated users
          docker exec pki find /var/log/pki/pki-tomcat \
              -name "localhost_access_log.*" \
              -exec cat {} \; \
              | tail -1 \
              | sed -e 's/^.* .* \(.*\) \[.*\] "\(.*\)" \(.*\) .*$/\2 \3 \1/' \
              | tee output

          cat > expected << EOF
          GET /pki/v1/info HTTP/1.1 200 -
          EOF

          diff expected output

      - name: Check pki ca-cert-find with default API
        if: false
        run: |
          docker exec client pki \
              -U https://pki.example.com:8443 \
              ca-cert-find \
              | tee output

          # get certs returned
          grep "Serial Number:" output | wc -l > actual

          # there should be 5 certs returned
          echo "5" > expected
          diff expected actual

          # get total certs found
          sed -n "s/^\(\S*\) entries found$/\1/p" output > actual

          # there should be no total certs found
          diff /dev/null actual

          # check HTTP methods, paths, protocols, status, and authenticated users
          docker exec pki find /var/log/pki/pki-tomcat \
              -name "localhost_access_log.*" \
              -exec cat {} \; \
              | tail -2 \
              | sed -e 's/^.* .* \(.*\) \[.*\] "\(.*\)" \(.*\) .*$/\2 \3 \1/' \
              | tee output

          cat > expected << EOF
          GET /pki/v2/info HTTP/1.1 200 -
          POST /ca/v2/certs/search HTTP/1.1 200 -
          EOF

          diff expected output

      - name: Check pki ca-cert-find with API v1
        if: false
        run: |
          docker exec client pki \
              -U https://pki.example.com:8443 \
              --api v1 \
              ca-cert-find \
              | tee output

          # get certs returned
          grep "Serial Number:" output | wc -l > actual

          # there should be 5 certs returned
          echo "5" > expected
          diff expected actual

          # get total certs found
          sed -n "s/^\(\S*\) entries found$/\1/p" output > actual

          # there should be 5 certs found
          echo "5" > expected
          diff expected actual

          # check HTTP methods, paths, protocols, status, and authenticated users
          docker exec pki find /var/log/pki/pki-tomcat \
              -name "localhost_access_log.*" \
              -exec cat {} \; \
              | tail -2 \
              | sed -e 's/^.* .* \(.*\) \[.*\] "\(.*\)" \(.*\) .*$/\2 \3 \1/' \
              | tee output

          cat > expected << EOF
          GET /pki/v1/info HTTP/1.1 200 -
          POST /ca/v1/certs/search HTTP/1.1 200 -
          EOF

          diff expected output

      - name: Check pki ca-user-show with default API
        if: false
        run: |
          docker exec client pki \
              -U https://pki.example.com:8443 \
              -n caadmin \
              ca-user-show \
              caadmin

          # check HTTP methods, paths, protocols, status, and authenticated users
          docker exec pki find /var/log/pki/pki-tomcat \
              -name "localhost_access_log.*" \
              -exec cat {} \; \
              | tail -4 \
              | sed -e 's/^.* .* \(.*\) \[.*\] "\(.*\)" \(.*\) .*$/\2 \3 \1/' \
              | tee output

          cat > expected << EOF
          GET /pki/v2/info HTTP/1.1 200 -
          GET /ca/v2/account/login HTTP/1.1 200 caadmin
          GET /ca/v2/admin/users/caadmin HTTP/1.1 200 caadmin
          GET /ca/v2/account/logout HTTP/1.1 204 caadmin
          EOF

          diff expected output

      - name: Check pki ca-user-show with API v1
        if: false
        run: |
          docker exec client pki \
              -U https://pki.example.com:8443 \
              -n caadmin \
              --api v1 \
              ca-user-show \
              caadmin

          # check HTTP methods, paths, protocols, status, and authenticated users
          docker exec pki find /var/log/pki/pki-tomcat \
              -name "localhost_access_log.*" \
              -exec cat {} \; \
              | tail -4 \
              | sed -e 's/^.* .* \(.*\) \[.*\] "\(.*\)" \(.*\) .*$/\2 \3 \1/' \
              | tee output

          cat > expected << EOF
          GET /pki/v1/info HTTP/1.1 200 -
          GET /ca/v1/account/login HTTP/1.1 200 caadmin
          GET /ca/v1/admin/users/caadmin HTTP/1.1 200 caadmin
          GET /ca/v1/account/logout HTTP/1.1 204 caadmin
          EOF

          diff expected output

      - name: Check pki ca-cert-request-find with default API
        if: false
        run: |
          docker exec client pki \
              -U https://pki.example.com:8443 \
              -n caadmin \
              ca-cert-request-find

          # check HTTP methods, paths, protocols, status, and authenticated users
          docker exec pki find /var/log/pki/pki-tomcat \
              -name "localhost_access_log.*" \
              -exec cat {} \; \
              | tail -4 \
              | sed -e 's/^.* .* \(.*\) \[.*\] "\(.*\)" \(.*\) .*$/\2 \3 \1/' \
              | tee output

          cat > expected << EOF
          GET /pki/v2/info HTTP/1.1 200 -
          GET /ca/v2/account/login HTTP/1.1 200 caadmin
          GET /ca/v2/agent/certrequests HTTP/1.1 200 caadmin
          GET /ca/v2/account/logout HTTP/1.1 204 caadmin
          EOF

          diff expected output

      - name: Check pki ca-cert-request-find with API v1
        if: false
        run: |
          docker exec client pki \
              -U https://pki.example.com:8443 \
              -n caadmin \
              --api v1 \
              ca-cert-request-find

          # check HTTP methods, paths, protocols, status, and authenticated users
          docker exec pki find /var/log/pki/pki-tomcat \
              -name "localhost_access_log.*" \
              -exec cat {} \; \
              | tail -4 \
              | sed -e 's/^.* .* \(.*\) \[.*\] "\(.*\)" \(.*\) .*$/\2 \3 \1/' \
              | tee output

          cat > expected << EOF
          GET /pki/v1/info HTTP/1.1 200 -
          GET /ca/v1/account/login HTTP/1.1 200 caadmin
          GET /ca/v1/agent/certrequests HTTP/1.1 200 caadmin
          GET /ca/v1/account/logout HTTP/1.1 204 caadmin
          EOF

          diff expected output

      - name: Get install token
        run: |
          docker exec client curl \
              -k \
              -s \
              -H "Accept: application/json" \
              --user caadmin:Secret.123 \
              --cookie-jar $SHARED/cookies \
              https://pki.example.com:8443/ca/rest/account/login \
              | python -m json.tool

          cat cookies

          # TODO: create a CLI for this operation
          docker exec client curl \
              -k \
              -s \
              --cookie $SHARED/cookies \
              "https://pki.example.com:8443/ca/rest/securityDomain/installToken?hostname=client.example.com&subsystem=KRA" \
              | python -m json.tool \
              | tee response.json

          jq -r '.token' response.json > install-token

      - name: Check pki ca-cert-issue with default API
        run: |
          # create CSR
          docker exec pki pki-server cert-request \
              --subject "CN=Audit Signing Certificate" \
              --ext /usr/share/pki/server/certs/audit_signing.conf \
              ca_audit_signing

          docker cp pki:/var/lib/pki/pki-tomcat/conf/certs/ca_audit_signing.csr .

          cat > expected << EOF
          GET /ca/ocsp/XXXXX HTTP/1.0 400 -
          POST /ca/ocsp HTTP/1.0 200 -
          GET /pki/v2/info HTTP/1.1 200 -
          GET /ca/v2/certrequests/profiles/caInternalAuthAuditSigningCert HTTP/1.1 200 -
          POST /ca/admin/ca/tokenAuthenticate HTTP/1.1 200 -
          POST /ca/ee/ca/profileSubmit HTTP/1.1 200 -
          EOF

          for i in {1..10}; do

              # issue cert
              docker exec client pki \
                  -U https://pki.example.com:8443 \
                  ca-cert-issue \
                  --install-token $SHARED/install-token \
                  --profile caInternalAuthAuditSigningCert \
                  --csr-file $SHARED/ca_audit_signing.csr \
                  --output-file ca_audit_signing.crt

              # check HTTP methods, paths, protocols, status, and authenticated users
              docker exec pki find /var/log/pki/pki-tomcat \
                  -name "localhost_access_log.*" \
                  -exec cat {} \; \
                  | tail -6 \
                  | sed -e 's/^.* .* \(.*\) \[.*\] "\(.*\)" \(.*\) .*$/\2 \3 \1/' \
                  | tee output

              # normalize output
              sed \
                  -e 's/^\(GET \/ca\/ocsp\/\)[^ ]* \(.*\)$/\1XXXXX \2/' \
                  output > actual

              diff expected actual || true

          done

      - name: Check pki ca-cert-issue with API v1
        run: |
          cat > expected << EOF
          GET /ca/ocsp/XXXXX HTTP/1.0 400 -
          POST /ca/ocsp HTTP/1.0 200 -
          GET /pki/v1/info HTTP/1.1 200 -
          GET /ca/v1/certrequests/profiles/caInternalAuthAuditSigningCert HTTP/1.1 200 -
          POST /ca/admin/ca/tokenAuthenticate HTTP/1.1 200 -
          POST /ca/ee/ca/profileSubmit HTTP/1.1 200 -
          EOF

          for i in {1..10}; do

              # issue cert
              docker exec client pki \
                  -U https://pki.example.com:8443 \
                  --api v1 \
                  ca-cert-issue \
                  --install-token $SHARED/install-token \
                  --profile caInternalAuthAuditSigningCert \
                  --csr-file $SHARED/ca_audit_signing.csr \
                  --output-file ca_audit_signing.crt

              # check HTTP methods, paths, protocols, status, and authenticated users
              docker exec pki find /var/log/pki/pki-tomcat \
                  -name "localhost_access_log.*" \
                  -exec cat {} \; \
                  | tail -6 \
                  | sed -e 's/^.* .* \(.*\) \[.*\] "\(.*\)" \(.*\) .*$/\2 \3 \1/' \
                  | tee output

              # normalize output
              sed \
                  -e 's/^\(GET \/ca\/ocsp\/\)[^ ]* \(.*\)$/\1XXXXX \2/' \
                  output > actual

              diff expected actual || true

          done

      - name: Check pki ca-sd-join and ca-sd-leave with default API
        run: |
          cat > expected << EOF
          GET /ca/ocsp/XXXXX HTTP/1.0 400 -
          POST /ca/ocsp HTTP/1.0 200 -
          GET /pki/v2/info HTTP/1.1 200 -
          POST /ca/admin/ca/tokenAuthenticate HTTP/1.1 200 -
          POST /ca/admin/ca/updateDomainXML HTTP/1.1 200 -
          GET /ca/ocsp/XXXXX HTTP/1.0 400 -
          POST /ca/ocsp HTTP/1.0 200 -
          GET /pki/v2/info HTTP/1.1 200 -
          GET /ca/v2/account/login HTTP/1.1 200 CA-pki.example.com-8443
          POST /ca/agent/ca/updateDomainXML HTTP/1.1 200 CA-pki.example.com-8443
          GET /ca/v2/account/logout HTTP/1.1 204 CA-pki.example.com-8443
          EOF

          for i in {1..10}; do

              docker exec client pki \
                  -U https://pki.example.com:8443 \
                  ca-sd-join \
                  --install-token $SHARED/install-token \
                  --type KRA \
                  --hostname client.example.com \
                  --secure-port 8443 \
                  "KRA client.example.com 8443"

              docker exec client pki \
                  -U https://pki.example.com:8443 \
                  -n subsystem \
                  ca-sd-leave \
                  --type KRA \
                  --hostname client.example.com \
                  --secure-port 8443 \
                  "KRA client.example.com 8443"

              # check HTTP methods, paths, protocols, status, and authenticated users
              docker exec pki find /var/log/pki/pki-tomcat \
                  -name "localhost_access_log.*" \
                  -exec cat {} \; \
                  | tail -11 \
                  | sed -e 's/^.* .* \(.*\) \[.*\] "\(.*\)" \(.*\) .*$/\2 \3 \1/' \
                  | tee output

              # normalize output
              sed \
                  -e 's/^\(GET \/ca\/ocsp\/\)[^ ]* \(.*\)$/\1XXXXX \2/' \
                  output > actual

              diff expected actual || true

          done


      - name: Check pki ca-sd-join and ca-sd-leave with API v1
        run: |
          cat > expected << EOF
          GET /ca/ocsp/XXXXX HTTP/1.0 400 -
          POST /ca/ocsp HTTP/1.0 200 -
          GET /pki/v1/info HTTP/1.1 200 -
          POST /ca/admin/ca/tokenAuthenticate HTTP/1.1 200 -
          POST /ca/admin/ca/updateDomainXML HTTP/1.1 200 -
          GET /ca/ocsp/XXXXX HTTP/1.0 400 -
          POST /ca/ocsp HTTP/1.0 200 -
          GET /pki/v1/info HTTP/1.1 200 -
          GET /ca/v1/account/login HTTP/1.1 200 CA-pki.example.com-8443
          POST /ca/agent/ca/updateDomainXML HTTP/1.1 200 CA-pki.example.com-8443
          GET /ca/v1/account/logout HTTP/1.1 204 CA-pki.example.com-8443
          EOF

          for i in {1..10}; do

              docker exec client pki \
                  -U https://pki.example.com:8443 \
                  --api v1 \
                  ca-sd-join \
                  --install-token $SHARED/install-token \
                  --type KRA \
                  --hostname client.example.com \
                  --secure-port 8443 \
                  "KRA client.example.com 8443"

              docker exec client pki \
                  -U https://pki.example.com:8443 \
                  -n subsystem \
                  --api v1 \
                  ca-sd-leave \
                  --type KRA \
                  --hostname client.example.com \
                  --secure-port 8443 \
                  "KRA client.example.com 8443"

              # check HTTP methods, paths, protocols, status, and authenticated users
              docker exec pki find /var/log/pki/pki-tomcat \
                  -name "localhost_access_log.*" \
                  -exec cat {} \; \
                  | tail -11 \
                  | sed -e 's/^.* .* \(.*\) \[.*\] "\(.*\)" \(.*\) .*$/\2 \3 \1/' \
                  | tee output

              # normalize output
              sed \
                  -e 's/^\(GET \/ca\/ocsp\/\)[^ ]* \(.*\)$/\1XXXXX \2/' \
                  output > actual

              diff expected actual || true

          done

      - name: Check DS server systemd journal
        if: always()
        run: |
          docker exec ds journalctl -x --no-pager -u dirsrv@localhost.service

      - name: Check DS container logs
        if: always()
        run: |
          docker logs ds

      - name: Check for PKI core dumps
        if: failure()
        run: |
          docker exec pki ls -l
          docker exec pki find / -path /proc -prune -o -name "hs_err_pid*.log" -exec cat {} \;

      - name: Check PKI server systemd journal
        if: always()
        run: |
          docker exec pki journalctl -x --no-pager -u pki-tomcatd@pki-tomcat.service

      - name: Check PKI server access log
        if: always()
        run: |
          docker exec pki find /var/log/pki/pki-tomcat -name "localhost_access_log.*" -exec cat {} \;

      - name: Check CA debug log
        if: always()
        run: |
          docker exec pki find /var/lib/pki/pki-tomcat/logs/ca -name "debug.*" -exec cat {} \;

      - name: Check for client core dumps
        if: failure()
        run: |
          docker exec client ls -l
          docker exec client find / -path /proc -prune -o -name "hs_err_pid*.log" -exec cat {} \;
