name: CA admin user

on:
  workflow_call:
    inputs:
      db-image:
        required: false
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Retrieve PKI images
        uses: actions/cache@v3
        with:
          key: pki-images-${{ github.sha }}
          path: pki-images.tar

      - name: Load PKI images
        run: docker load --input pki-images.tar

      - name: Create network
        run: docker network create example

      - name: Set up DS container
        run: |
          tests/bin/ds-container-create.sh ds
        env:
          IMAGE: ${{ inputs.db-image }}
          HOSTNAME: ds.example.com
          PASSWORD: Secret.123

      - name: Connect DS container to network
        run: docker network connect example ds --alias ds.example.com

      - name: Set up PKI container
        run: |
          tests/bin/runner-init.sh pki
        env:
          HOSTNAME: pki.example.com

      - name: Connect PKI container to network
        run: docker network connect example pki --alias pki.example.com

      - name: Install CA without default admin
        run: |
          docker exec pki pkispawn \
              -f /usr/share/pki/server/examples/installation/ca.cfg \
              -s CA \
              -D pki_ds_url=ldap://ds.example.com:3389 \
              -D pki_cert_id_generator=random \
              -D pki_request_id_generator=random \
              -D pki_admin_setup=False \
              -v

      - name: Check CA users
        run: |
          docker exec pki pki-server ca-user-find | tee output

      - name: Check CA groups
        run: |
          docker exec pki pki-server ca-group-find | tee output

      - name: Add CA admin user
        run: |
          docker exec pki pki-server ca-user-add caadmin \
              --full-name Administrator \
              --password Secret.123 \
              --type adminType \
              --state 1

          docker exec pki pki-server ca-user-show caadmin | tee output

          echo "adminType" > expected
          sed -n 's/^ *Type: *\(.*\)$/\1/p' output > actual
          diff expected actual

      - name: Grant Administrators role to CA admin user
        run: |
          docker exec pki pki-server ca-user-role-add caadmin Administrators

          docker exec pki pki-server ca-user-role-find caadmin | tee output

          echo "Administrators" > expected
          sed -n 's/^ *Role ID: *\(.*\)$/\1/p' output | sort > actual
          diff expected actual

      - name: Check auth with CA admin password
        run: |
          # import CA signing cert
          docker exec pki pki-server cert-export ca_signing --cert-file ca_signing.crt
          docker exec pki pki client-cert-import ca_signing --ca-cert ca_signing.crt

          # correct password should work
          docker exec pki pki -u caadmin -w Secret.123 ca-user-find

          # wrong password should not work
          docker exec pki pki -u caadmin -w wrong ca-user-find \
              > >(tee stdout) 2> >(tee stderr >&2) || true

          echo "PKIException: Unauthorized" > expected
          diff expected stderr

      - name: Change CA admin password
        run: |
          docker exec pki pki-server ca-user-mod --password new caadmin

          # original password should no longer work
          docker exec pki pki -u caadmin -w Secret.123 ca-user-find \
              > >(tee stdout) 2> >(tee stderr >&2) || true

          echo "PKIException: Unauthorized" > expected
          diff expected stderr

          # new password should work
          docker exec pki pki -u caadmin -w new ca-user-find

      - name: Change CA admin password with file
        run: |
          echo secret > secret.txt
          docker exec pki pki-server ca-user-mod --password-file $SHARED/secret.txt caadmin

          # password file should work
          docker exec pki pki -u caadmin -w secret ca-user-find

      - name: Remove CA admin password
        run: |
          docker exec pki pki-server ca-user-mod --password "" caadmin

          # old password should no longer work
          docker exec pki pki -u caadmin -w secret ca-user-find \
              > >(tee stdout) 2> >(tee stderr >&2) || true

          echo "PKIException: Unauthorized" > expected
          diff expected stderr

          # blank password should not work
          docker exec pki pki -u caadmin -w "" ca-user-find \
              > >(tee stdout) 2> >(tee stderr >&2) || true

          echo "PKIException: Unauthorized" > expected
          diff expected stderr

      - name: Generate CA admin cert
        run: |
          # generate cert request
          docker exec pki pki nss-cert-request \
              --subject "CN=Administrator" \
              --ext /usr/share/pki/server/certs/admin.conf \
              --csr caadmin.csr

          # issue cert
          docker exec pki pki \
              -d /etc/pki/pki-tomcat/alias \
              -f /etc/pki/pki-tomcat/password.conf \
              nss-cert-issue \
              --issuer ca_signing \
              --csr caadmin.csr \
              --ext /usr/share/pki/server/certs/admin.conf \
              --cert caadmin.crt

      - name: Check auth with CA admin cert
        run: |
          # import cert
          docker exec pki pki nss-cert-import --cert caadmin.crt caadmin

          # get cert serial number
          docker exec pki pki nss-cert-show caadmin | tee output
          sed -n 's/^ *Serial Number: *\(.*\)$/\1/p' output > cert.sn

          # assign cert to user
          docker exec pki pki-server ca-user-cert-add --cert caadmin.crt caadmin

          # check assigned cert serial number
          docker exec pki pki-server ca-user-cert-find caadmin | tee output
          sed -n 's/^ *Serial Number: *\(.*\)$/\1/p' output > actual
          diff cert.sn actual

          # get assigned cert ID
          sed -n 's/^ *Cert ID: *\(.*\)$/\1/p' output > cert.id
          CERT_ID=$(cat cert.id)
          echo "CERT_ID: $CERT_ID"

          # auth with admin cert should work
          docker exec pki pki -n caadmin ca-user-find

      - name: Unassign certs from CA admin user
        run: |
          CERT_ID=$(cat cert.id)
          echo "CERT_ID: $CERT_ID"

          docker exec pki pki-server ca-user-cert-del caadmin "$CERT_ID"

          # admin user should have no certs
          docker exec pki pki-server ca-user-cert-find caadmin | tee actual
          diff /dev/null actual

          # auth with admin cert should no longer work
          docker exec pki pki -n caadmin ca-user-find \
              > >(tee stdout) 2> >(tee stderr >&2) || true

          echo "PKIException: Unauthorized" > expected
          diff expected stderr

      - name: Reassign certs to CA admin user
        run: |
          CERT_ID=$(cat cert.id)
          echo "CERT_ID: $CERT_ID"

          docker exec pki pki-server ca-user-cert-add --cert caadmin.crt caadmin

          # new admin cert ID should match the original admin cert ID
          docker exec pki pki-server ca-user-cert-find caadmin | tee output
          sed -n 's/^ *Cert ID: *\(.*\)$/\1/p' output > actual
          diff cert.id actual

          # auth with admin cert should work again
          docker exec pki pki -n caadmin ca-user-find

      - name: Remove Administrators role from CA admin user
        run: |
          docker exec pki pki-server ca-user-role-del caadmin Administrators

      - name: Authorization with CA admin cert should not work
        run: |
          docker exec pki pki -n caadmin ca-user-find \
              > >(tee stdout) 2> >(tee stderr >&2) || true

          echo "ForbiddenException: Authorization Error" > expected
          diff expected stderr

      - name: Restore Administrators role for CA admin user
        run: |
          docker exec pki pki-server ca-user-role-add caadmin Administrators

      - name: Authorization with CA admin cert should work again
        run: |
          docker exec pki pki -n caadmin ca-user-find

      - name: Gather artifacts
        if: always()
        run: |
          tests/bin/ds-artifacts-save.sh --output=/tmp/artifacts/pki ds
          tests/bin/pki-artifacts-save.sh pki
        continue-on-error: true

      - name: Remove CA
        run: docker exec pki pkidestroy -i pki-tomcat -s CA -v

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ca-admin-user
          path: |
            /tmp/artifacts/pki
