name: CA Clone Tests

on: [push, pull_request]

jobs:
  build:
    name: Waiting for build
    uses: ./.github/workflows/wait-for-build.yml
    secrets: inherit

  ca-clone-test:
    name: CA clone
    needs: build
    uses: ./.github/workflows/ca-clone-test.yml

  ca-clone-sequential-test:
    name: CA clone with Sequential Serial Numbers
    needs: build
    uses: ./.github/workflows/ca-clone-sequential-test.yml
