name: CA Tests

on: [push, pull_request]

jobs:
  build:
    name: Waiting for build
    uses: ./.github/workflows/wait-for-build.yml
    secrets: inherit

  ca-basic-test:
    name: Basic CA
    needs: build
    uses: ./.github/workflows/ca-basic-test.yml

  ca-ssnv1-test:
    name: CA with SSNv1
    needs: build
    uses: ./.github/workflows/ca-ssnv1-test.yml

  ca-ssnv2-test:
    name: CA with SSNv2
    needs: build
    uses: ./.github/workflows/ca-ssnv2-test.yml
