name: CA Tests

on: [push, pull_request]

jobs:
  build:
    name: Waiting for build
    uses: ./.github/workflows/wait-for-build.yml
    secrets: inherit

  ca-basic-test:
    name: Basic CA
    needs: build
    uses: ./.github/workflows/ca-basic-test.yml

  ca-sequential-test:
    name: CA with Sequential Serial Numbers
    needs: build
    uses: ./.github/workflows/ca-sequential-test.yml
