name: IPA Tests

on: [push, pull_request]

jobs:
  init:
    name: Initialization
    uses: ./.github/workflows/init.yml
    secrets: inherit

  build:
    name: Building IPA images
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        id: cache-buildx
        uses: actions/cache@v3
        with:
          key: buildx-${{ hashFiles('pki.spec') }}
          path: /tmp/.buildx-cache

      - name: Build pki-runner image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ needs.init.outputs.base-image }}
            COPR_REPO=${{ needs.init.outputs.repo }}
          tags: pki-runner
          target: pki-runner
          cache-from: type=local,src=/tmp/.buildx-cache
          outputs: type=docker

      - name: Build ipa-runner image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ needs.init.outputs.base-image }}
            COPR_REPO=${{ needs.init.outputs.repo }}
          tags: ipa-runner
          target: ipa-runner
          cache-from: type=local,src=/tmp/.buildx-cache
          outputs: type=docker

      - name: Save IPA images
        run: |
          docker images
          docker save -o ipa-images.tar pki-runner ipa-runner

      - name: Store IPA images
        uses: actions/cache@v3
        with:
          key: ipa-images-${{ github.sha }}
          path: ipa-images.tar

  ipa-basic-test:
    name: Basic IPA
    needs: [init, build]
    uses: ./.github/workflows/ipa-basic-test.yml
    with:
      db-image: ${{ needs.init.outputs.db-image }}

  ipa-migration-test:
    name: IPA migration
    needs: [init, build]
    uses: ./.github/workflows/ipa-migration-test.yml
    with:
      db-image: ${{ needs.init.outputs.db-image }}
