name: KRA with ECC
# This test will perform the following operations:
# - install CA with EC certs
# - install KRA with EC certs
# - enroll EC cert using CRMFPopClient without POP
# - recover cert key
# - enroll EC cert using CRMFPopClient with POP
# - recover cert key
# - enroll EC cert using PKI CLI without POP
# - recover cert key
# - enroll EC cert using PKI CLI with POP
# - recover cert key

on: workflow_call

env:
  DS_IMAGE: ${{ vars.DS_IMAGE || 'quay.io/389ds/dirsrv' }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Retrieve PKI images
        uses: actions/cache@v4
        with:
          key: pki-images-${{ github.sha }}
          path: pki-images.tar

      - name: Load PKI images
        run: docker load --input pki-images.tar

      - name: Create network
        run: docker network create example

      - name: Set up DS container
        run: |
          tests/bin/ds-create.sh \
              --image=${{ env.DS_IMAGE }} \
              --hostname=ds.example.com \
              --network=example \
              --network-alias=ds.example.com \
              --password=Secret.123 \
              ds

      - name: Set up PKI container
        run: |
          tests/bin/runner-init.sh \
              --hostname=pki.example.com \
              --network=example \
              --network-alias=pki.example.com \
              pki

          docker exec pki dnf install -y dumpasn1

      - name: Install CA with EC certs
        run: |
          docker exec pki pkispawn \
              -f /usr/share/pki/server/examples/installation/ca-ecc.cfg \
              -s CA \
              -D pki_ds_url=ldap://ds.example.com:3389 \
              -v

      - name: Install KRA with EC certs
        run: |
          # docs/installation/kra/Installing_KRA_with_ECC.md
          docker exec pki pkispawn \
              -f /usr/share/pki/server/examples/installation/kra-ecc.cfg \
              -s KRA \
              -D pki_ds_url=ldap://ds.example.com:3389 \
              -v

      - name: Check KRA storage cert
        run: |
          docker exec pki openssl req -text -noout \
              -in /var/lib/pki/pki-tomcat/conf/certs/kra_storage.csr

          docker exec pki pki-server cert-export kra_storage \
              --cert-file kra_storage.crt
          docker exec pki openssl x509 -text -noout -in kra_storage.crt | tee output

          # public key algorithm should be "rsaEncryption"
          echo "rsaEncryption" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Public Key Algorithm:\s*\(.*\)$/\1/p" output > actual
          diff expected actual

          # signing algorithm should be "ecdsa-with-SHA512"
          echo "ecdsa-with-SHA512" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # default signing algorithm should not exist
          echo "ERROR: No such parameter: kra.storage.defaultSigningAlgorithm" > expected
          docker exec pki pki-server kra-config-show kra.storage.defaultSigningAlgorithm \
              > >(tee stdout) 2> >(tee stderr >&2) || true
          diff expected stderr

      - name: Check KRA transport cert
        run: |
          docker exec pki openssl req -text -noout \
              -in /var/lib/pki/pki-tomcat/conf/certs/kra_transport.csr

          docker exec pki pki-server cert-export kra_transport \
              --cert-file kra_transport.crt
          docker exec pki openssl x509 -text -noout -in kra_transport.crt | tee output

          # public key algorithm should be "rsaEncryption"
          echo "rsaEncryption" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Public Key Algorithm:\s*\(.*\)$/\1/p" output > actual
          diff expected actual

          # signing algorithm should be "ecdsa-with-SHA512"
          echo "ecdsa-with-SHA512" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # default signing algorithm should not exist
          echo "ERROR: No such parameter: kra.transport.defaultSigningAlgorithm" > expected
          docker exec pki pki-server kra-config-show kra.transport.defaultSigningAlgorithm \
              > >(tee stdout) 2> >(tee stderr >&2) || true
          diff expected stderr

      - name: Check KRA audit signing cert
        run: |
          docker exec pki openssl req -text -noout \
              -in /var/lib/pki/pki-tomcat/conf/certs/kra_audit_signing.csr

          docker exec pki pki-server cert-export kra_audit_signing \
              --cert-file kra_audit_signing.crt
          docker exec pki openssl x509 -text -noout -in kra_audit_signing.crt | tee output

          # public key algorithm should be "id-ecPublicKey"
          echo "id-ecPublicKey" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Public Key Algorithm:\s*\(.*\)$/\1/p" output > actual
          diff expected actual

          # signing algorithm should be "ecdsa-with-SHA512"
          echo "ecdsa-with-SHA512" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # default signing algorithm should be "SHA384withEC"
          echo "SHA384withEC" > expected
          docker exec pki pki-server kra-config-show kra.audit_signing.defaultSigningAlgorithm | tee actual
          diff expected actual

      - name: Check subsystem cert
        run: |
          docker exec pki openssl req -text -noout \
              -in /var/lib/pki/pki-tomcat/conf/certs/subsystem.csr

          docker exec pki pki-server cert-export subsystem \
              --cert-file subsystem.crt
          docker exec pki openssl x509 -text -noout -in subsystem.crt | tee output

          # public key algorithm should be "id-ecPublicKey"
          echo "id-ecPublicKey" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Public Key Algorithm:\s*\(.*\)$/\1/p" output > actual
          diff expected actual

          # signing algorithm should be "ecdsa-with-SHA512"
          echo "ecdsa-with-SHA512" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # default signing algorithm should not exist
          echo "ERROR: No such parameter: kra.subsystem.defaultSigningAlgorithm" > expected
          docker exec pki pki-server kra-config-show kra.subsystem.defaultSigningAlgorithm \
              > >(tee stdout) 2> >(tee stderr >&2) || true
          diff expected stderr

      - name: Check SSL server cert
        run: |
          docker exec pki openssl req -text -noout \
              -in /var/lib/pki/pki-tomcat/conf/certs/sslserver.csr

          docker exec pki pki-server cert-export sslserver \
              --cert-file sslserver.crt
          docker exec pki openssl x509 -text -noout -in sslserver.crt | tee output

          # public key algorithm should be "id-ecPublicKey"
          echo "id-ecPublicKey" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Public Key Algorithm:\s*\(.*\)$/\1/p" output > actual
          diff expected actual

          # signing algorithm should be "ecdsa-with-SHA512"
          echo "ecdsa-with-SHA512" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

          # default signing algorithm should not exist
          echo "ERROR: No such parameter: kra.sslserver.defaultSigningAlgorithm" > expected
          docker exec pki pki-server kra-config-show kra.sslserver.defaultSigningAlgorithm \
              > >(tee stdout) 2> >(tee stderr >&2) || true
          diff expected stderr

      - name: Check KRA admin cert
        run: |
          docker exec pki openssl x509 -text -noout \
              -in /root/.dogtag/pki-tomcat/ca_admin.cert | tee output

          # public key algorithm should be "id-ecPublicKey"
          echo "id-ecPublicKey" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Public Key Algorithm:\s*\(.*\)$/\1/p" output > actual
          diff expected actual

          # signing algorithm should be "ecdsa-with-SHA512"
          echo "ecdsa-with-SHA512" > expected
          sed -n -e "s/\s*$//" -e "s/^\s*Signature Algorithm:\s*\(.*\)$/\1/p" output | uniq > actual
          diff expected actual

      - name: Run PKI healthcheck
        run: docker exec pki pki-healthcheck --failures-only

      - name: Import CA signing cert
        run: |
          docker exec pki pki-server cert-export \
              --cert-file ca_signing.crt \
              ca_signing

          docker exec pki pki nss-cert-import \
              --cert ca_signing.crt \
              --trust CT,C,C \
              ca_signing

      - name: Import KRA transport cert
        run: |
          docker exec pki pki nss-cert-import \
              --cert kra_transport.crt \
              kra_transport

      - name: Check KRA admin
        run: |
          docker exec pki pki pkcs12-import \
              --pkcs12 /root/.dogtag/pki-tomcat/ca_admin_cert.p12 \
              --pkcs12-password Secret.123
          docker exec pki pki -n caadmin kra-user-show kraadmin

      - name: Enable caECUserCert profile
        run: |
          docker exec pki pki-server ca-profile-mod --enable true caECUserCert
          docker exec pki pki-server restart --wait

      - name: Enroll EC cert using CRMFPopClient without POP
        run: |
          # generate key and cert request
          # NOTE: EC key requires -t false
          docker exec pki CRMFPopClient \
              -d /root/.dogtag/nssdb \
              -p "" \
              -f caECUserCert \
              -a ec \
              -t false \
              -q POP_NONE \
              -n UID=test-CRMFPopClient-without-POP \
              -u test-CRMFPopClient-without-POP \
              -r test-CRMFPopClient-without-POP \
              -b kra_transport.crt \
              -o test-CRMFPopClient-without-POP.csr | tee output

          docker exec pki cat test-CRMFPopClient-without-POP.csr

          docker exec pki AtoB test-CRMFPopClient-without-POP.csr test-CRMFPopClient-without-POP.der
          docker exec pki dumpasn1 test-CRMFPopClient-without-POP.der

          # issue cert
          docker exec pki pki \
              -u caadmin \
              -w Secret.123 \
              ca-cert-issue \
              --request-type crmf \
              --profile caECUserCert \
              --subject UID=test-CRMFPopClient-without-POP \
              --csr-file test-CRMFPopClient-without-POP.csr \
              --output-file test-CRMFPopClient-without-POP.crt | tee output

          # import cert into NSS database
          docker exec pki pki nss-cert-import \
              --cert test-CRMFPopClient-without-POP.crt \
              test-CRMFPopClient-without-POP

          docker exec pki pki nss-cert-show test-CRMFPopClient-without-POP | tee output

          # normalize output
          sed \
              -e '/^ *Serial Number:/d' \
              -e '/^ *Not Valid Before:/d' \
              -e '/^ *Not Valid After:/d' \
              output > actual

          # the cert should match the key (trust flags must be u,u,u)
          cat > expected << EOF
            Nickname: test-CRMFPopClient-without-POP
            Subject DN: UID=test-CRMFPopClient-without-POP
            Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
            Trust Flags: u,u,u
          EOF

          diff expected actual

      - name: Check key requests after enrollment
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-request-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/entries matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 1 key request
          cat > expected << EOF
            Type: enrollment
            Status: complete
          EOF

          diff expected actual

      - name: Check keys after enrollment
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/key(s) matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 1 key
          # NOTE: EC key size is -1
          cat > expected << EOF
            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-CRMFPopClient-without-POP
          EOF

          diff expected actual

      - name: Check key record after enrollment
        run: |
          # find archived key by owner
          docker exec pki pki \
              -u kraadmin \
              -w Secret.123 \
              kra-key-find \
              --owner UID=test-CRMFPopClient-without-POP \
              | tee output

          KEY_ID=$(sed -n "s/^\s*Key ID:\s*\(\S*\)$/\1/p" output)
          echo "Key ID: $KEY_ID"
          echo $KEY_ID > cert.key_id

          DEC_KEY_ID=$(python -c "print(int('$KEY_ID', 16))")
          echo "Dec Key ID: $DEC_KEY_ID"

          # get key record
          docker exec pki ldapsearch \
              -H ldap://ds.example.com:3389 \
              -x \
              -D "cn=Directory Manager" \
              -w Secret.123 \
              -b "cn=$DEC_KEY_ID,ou=keyRepository,ou=kra,dc=kra,dc=pki,dc=example,dc=com" \
              -o ldif_wrap=no \
              -LLL | tee output

          # normalize output
          sed \
              -e '/^$/d' \
              -e 's/^\(serialno\): .*$/\1: XXXXX/' \
              -e 's/^\(privateKeyData\):: .*$/\1:: XXXXX/' \
              -e 's/^\(publicKeyData\):: .*$/\1:: XXXXX/' \
              -e 's/^\(metaInfo: payloadEncryptionIV\):.*/\1:XXXXX/' \
              -e 's/^\(dateOfCreate\): .*$/\1: XXXXX/' \
              -e 's/^\(dateOfModify\): .*$/\1: XXXXX/' \
              output > actual

          cat > expected << EOF
          dn: cn=$DEC_KEY_ID,ou=keyRepository,ou=kra,dc=kra,dc=pki,dc=example,dc=com
          objectClass: top
          objectClass: keyRecord
          keyState: VALID
          serialno: XXXXX
          ownerName: UID=test-CRMFPopClient-without-POP
          keySize: -1
          algorithm: 1.2.840.10045.2.1
          privateKeyData:: XXXXX
          publicKeyData:: XXXXX
          metaInfo: payloadEncrypted:false
          metaInfo: sessionKeyLength:128
          metaInfo: sessionKeyWrapAlgorithm:RSA
          metaInfo: sessionKeyKeyGenAlgorithm:AES
          metaInfo: payloadEncryptionOID:2.16.840.1.101.3.4.1.2
          metaInfo: payloadEncryptionIV:XXXXX
          metaInfo: payloadWrapAlgorithm:AES KeyWrap/Padding
          metaInfo: EllipticCurve:ANSI X9.62 elliptic curve prime256v1 (aka secp256r1, NIST P-256)
          metaInfo: sessionKeyType:AES
          dateOfCreate: XXXXX
          dateOfModify: XXXXX
          archivedBy: CA-pki.example.com-8443
          cn: $DEC_KEY_ID
          EOF

          diff expected actual

      - name: Recover cert key
        run: |
          KEY_ID=$(cat cert.key_id)
          echo "Key ID: $KEY_ID"

          # export cert into Base64-encoded format
          BASE64_CERT=$(docker exec pki pki nss-cert-export \
              --format DER \
              test-CRMFPopClient-without-POP \
              | base64 --wrap=0)
          echo "Cert: $BASE64_CERT"

          # create retrieval request with key ID, cert, and passphrase
          cat > request.json <<EOF
          {
            "ClassName" : "com.netscape.certsrv.key.KeyRecoveryRequest",
            "Attributes" : {
              "Attribute" : [ {
                "name" : "keyId",
                "value" : "$KEY_ID"
              }, {
                "name" : "certificate",
                "value" : "$BASE64_CERT"
              }, {
                "name" : "passphrase",
                "value" : "Secret.123"
              } ]
            }
          }
          EOF

          # retrieve archived cert and key into PKCS #12 file
          # https://github.com/dogtagpki/pki/wiki/Retrieving-Archived-Key
          docker exec pki pki \
              -n caadmin \
              kra-key-retrieve \
              --input $SHARED/request.json \
              --transport kra_transport \
              --output-data test-CRMFPopClient-without-POP.p12

          # import PKCS #12 file into NSS database with the passphrase
          docker exec pki pki \
              -d nssdb \
              pkcs12-import \
              --pkcs12 test-CRMFPopClient-without-POP.p12 \
              --password Secret.123

          # remove archived cert from NSS database
          docker exec pki pki -d nssdb nss-cert-del UID=test-CRMFPopClient-without-POP

          # import original cert into NSS database
          docker exec pki pki \
              -d nssdb \
              nss-cert-import \
              --cert test-CRMFPopClient-without-POP.crt \
              test-CRMFPopClient-without-POP

          docker exec pki pki -d nssdb nss-cert-show test-CRMFPopClient-without-POP | tee output

          # normalize output
          sed \
              -e '/^ *Serial Number:/d' \
              -e '/^ *Not Valid Before:/d' \
              -e '/^ *Not Valid After:/d' \
              output > actual

          # the cert should match the key (trust flags must be u,u,u)
          cat > expected << EOF
            Nickname: test-CRMFPopClient-without-POP
            Subject DN: UID=test-CRMFPopClient-without-POP
            Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
            Trust Flags: u,u,u
          EOF

          diff expected actual

      - name: Check key requests after recovery
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-request-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/entries matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 2 key requests
          cat > expected << EOF
            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete
          EOF

          diff expected actual

      - name: Check keys after recovery
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/key(s) matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 1 key
          # NOTE: test-CRMFPopClient-without-POP key don't have a status
          cat > expected << EOF
            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-CRMFPopClient-without-POP
          EOF

          diff expected actual

      - name: Enroll EC cert using CRMFPopClient with POP
        run: |
          # generate key and cert request
          # NOTE: EC key requires -t false
          docker exec pki CRMFPopClient \
              -d /root/.dogtag/nssdb \
              -p "" \
              -f caECUserCert \
              -a ec \
              -t false \
              -n UID=test-CRMFPopClient-with-POP \
              -u test-CRMFPopClient-with-POP \
              -r test-CRMFPopClient-with-POP \
              -b kra_transport.crt \
              -o test-CRMFPopClient-with-POP.csr | tee output

          docker exec pki cat test-CRMFPopClient-with-POP.csr

          docker exec pki AtoB test-CRMFPopClient-with-POP.csr test-CRMFPopClient-with-POP.der
          docker exec pki dumpasn1 test-CRMFPopClient-with-POP.der

          # issue cert
          docker exec pki pki \
              -u caadmin \
              -w Secret.123 \
              ca-cert-issue \
              --request-type crmf \
              --profile caECUserCert \
              --subject UID=test-CRMFPopClient-with-POP \
              --csr-file test-CRMFPopClient-with-POP.csr \
              --output-file test-CRMFPopClient-with-POP.crt | tee output

          # import cert into NSS database
          docker exec pki pki nss-cert-import \
              --cert test-CRMFPopClient-with-POP.crt \
              test-CRMFPopClient-with-POP

          docker exec pki pki nss-cert-show test-CRMFPopClient-with-POP | tee output

          # normalize output
          sed \
              -e '/^ *Serial Number:/d' \
              -e '/^ *Not Valid Before:/d' \
              -e '/^ *Not Valid After:/d' \
              output > actual

          # the cert should match the key (trust flags must be u,u,u)
          cat > expected << EOF
            Nickname: test-CRMFPopClient-with-POP
            Subject DN: UID=test-CRMFPopClient-with-POP
            Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
            Trust Flags: u,u,u
          EOF

          diff expected actual

      - name: Check key requests after enrollment
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-request-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/entries matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 1 key request
          cat > expected << EOF
            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete

            Type: enrollment
            Status: complete
          EOF

          diff expected actual

      - name: Check keys after enrollment
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/key(s) matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 1 key
          # NOTE: EC key size is -1
          cat > expected << EOF
            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-CRMFPopClient-without-POP

            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-CRMFPopClient-with-POP
          EOF

          diff expected actual

      - name: Check key record after enrollment
        run: |
          # find archived key by owner
          docker exec pki pki \
              -u kraadmin \
              -w Secret.123 \
              kra-key-find \
              --owner UID=test-CRMFPopClient-with-POP \
              | tee output

          KEY_ID=$(sed -n "s/^\s*Key ID:\s*\(\S*\)$/\1/p" output)
          echo "Key ID: $KEY_ID"
          echo $KEY_ID > cert.key_id

          DEC_KEY_ID=$(python -c "print(int('$KEY_ID', 16))")
          echo "Dec Key ID: $DEC_KEY_ID"

          # get key record
          docker exec pki ldapsearch \
              -H ldap://ds.example.com:3389 \
              -x \
              -D "cn=Directory Manager" \
              -w Secret.123 \
              -b "cn=$DEC_KEY_ID,ou=keyRepository,ou=kra,dc=kra,dc=pki,dc=example,dc=com" \
              -o ldif_wrap=no \
              -LLL | tee output

          # normalize output
          sed \
              -e '/^$/d' \
              -e 's/^\(serialno\): .*$/\1: XXXXX/' \
              -e 's/^\(privateKeyData\):: .*$/\1:: XXXXX/' \
              -e 's/^\(publicKeyData\):: .*$/\1:: XXXXX/' \
              -e 's/^\(metaInfo: payloadEncryptionIV\):.*/\1:XXXXX/' \
              -e 's/^\(dateOfCreate\): .*$/\1: XXXXX/' \
              -e 's/^\(dateOfModify\): .*$/\1: XXXXX/' \
              output > actual

          cat > expected << EOF
          dn: cn=$DEC_KEY_ID,ou=keyRepository,ou=kra,dc=kra,dc=pki,dc=example,dc=com
          objectClass: top
          objectClass: keyRecord
          keyState: VALID
          serialno: XXXXX
          ownerName: UID=test-CRMFPopClient-with-POP
          keySize: -1
          algorithm: 1.2.840.10045.2.1
          privateKeyData:: XXXXX
          publicKeyData:: XXXXX
          metaInfo: payloadEncrypted:false
          metaInfo: sessionKeyLength:128
          metaInfo: sessionKeyWrapAlgorithm:RSA
          metaInfo: sessionKeyKeyGenAlgorithm:AES
          metaInfo: payloadEncryptionOID:2.16.840.1.101.3.4.1.2
          metaInfo: payloadEncryptionIV:XXXXX
          metaInfo: payloadWrapAlgorithm:AES KeyWrap/Padding
          metaInfo: EllipticCurve:ANSI X9.62 elliptic curve prime256v1 (aka secp256r1, NIST P-256)
          metaInfo: sessionKeyType:AES
          dateOfCreate: XXXXX
          dateOfModify: XXXXX
          archivedBy: CA-pki.example.com-8443
          cn: $DEC_KEY_ID
          EOF

          diff expected actual

      - name: Recover cert key
        run: |
          KEY_ID=$(cat cert.key_id)
          echo "Key ID: $KEY_ID"

          # export cert into Base64-encoded format
          BASE64_CERT=$(docker exec pki pki nss-cert-export \
              --format DER \
              test-CRMFPopClient-with-POP \
              | base64 --wrap=0)
          echo "Cert: $BASE64_CERT"

          # create retrieval request with key ID, cert, and passphrase
          cat > request.json <<EOF
          {
            "ClassName" : "com.netscape.certsrv.key.KeyRecoveryRequest",
            "Attributes" : {
              "Attribute" : [ {
                "name" : "keyId",
                "value" : "$KEY_ID"
              }, {
                "name" : "certificate",
                "value" : "$BASE64_CERT"
              }, {
                "name" : "passphrase",
                "value" : "Secret.123"
              } ]
            }
          }
          EOF

          # retrieve archived cert and key into PKCS #12 file
          # https://github.com/dogtagpki/pki/wiki/Retrieving-Archived-Key
          docker exec pki pki \
              -n caadmin \
              kra-key-retrieve \
              --input $SHARED/request.json \
              --transport kra_transport \
              --output-data test-CRMFPopClient-with-POP.p12

          # import PKCS #12 file into NSS database with the passphrase
          docker exec pki pki \
              -d nssdb \
              pkcs12-import \
              --pkcs12 test-CRMFPopClient-with-POP.p12 \
              --password Secret.123

          # remove archived cert from NSS database
          docker exec pki pki -d nssdb nss-cert-del UID=test-CRMFPopClient-with-POP

          # import original cert into NSS database
          docker exec pki pki \
              -d nssdb \
              nss-cert-import \
              --cert test-CRMFPopClient-with-POP.crt \
              test-CRMFPopClient-with-POP

          docker exec pki pki -d nssdb nss-cert-show test-CRMFPopClient-with-POP | tee output

          # normalize output
          sed \
              -e '/^ *Serial Number:/d' \
              -e '/^ *Not Valid Before:/d' \
              -e '/^ *Not Valid After:/d' \
              output > actual

          # the cert should match the key (trust flags must be u,u,u)
          cat > expected << EOF
            Nickname: test-CRMFPopClient-with-POP
            Subject DN: UID=test-CRMFPopClient-with-POP
            Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
            Trust Flags: u,u,u
          EOF

          diff expected actual

      - name: Check key requests after recovery
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-request-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/entries matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 2 key requests
          cat > expected << EOF
            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete

            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete
          EOF

          diff expected actual

      - name: Check keys after recovery
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/key(s) matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 1 key
          # NOTE: test-CRMFPopClient-with-POP and test-PKI-CLI-with-POP keys don't have a status
          cat > expected << EOF
            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-CRMFPopClient-without-POP

            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-CRMFPopClient-with-POP
          EOF

          diff expected actual

      - name: Enroll EC cert using PKI CLI without POP
        run: |
          # generate key and cert request
          # https://github.com/dogtagpki/pki/wiki/Generating-Certificate-Request-with-PKI-NSS
          docker exec pki pki nss-cert-request \
              --key-type EC \
              --curve nistp521 \
              --type crmf \
              --subject UID=test-PKI-CLI-without-POP \
              --transport kra_transport \
              --csr test-PKI-CLI-without-POP.csr

          docker exec pki cat test-PKI-CLI-without-POP.csr

          docker exec pki AtoB test-PKI-CLI-without-POP.csr test-PKI-CLI-without-POP.der
          docker exec pki dumpasn1 test-PKI-CLI-without-POP.der

          # issue cert
          # https://github.com/dogtagpki/pki/wiki/Issuing-Certificates
          docker exec pki pki \
              -u caadmin \
              -w Secret.123 \
              ca-cert-issue \
              --request-type crmf \
              --profile caECUserCert \
              --subject UID=test-PKI-CLI-without-POP \
              --csr-file test-PKI-CLI-without-POP.csr \
              --output-file test-PKI-CLI-without-POP.crt

          # import cert into NSS database
          docker exec pki pki nss-cert-import \
              --cert test-PKI-CLI-without-POP.crt \
              test-PKI-CLI-without-POP

          docker exec pki pki nss-cert-show test-PKI-CLI-without-POP | tee output

          # normalize output
          sed \
              -e '/^ *Serial Number:/d' \
              -e '/^ *Not Valid Before:/d' \
              -e '/^ *Not Valid After:/d' \
              output > actual

          # the cert should match the key (trust flags must be u,u,u)
          cat > expected << EOF
            Nickname: test-PKI-CLI-without-POP
            Subject DN: UID=test-PKI-CLI-without-POP
            Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
            Trust Flags: u,u,u
          EOF

          diff expected actual

      - name: Check key requests after enrollment
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-request-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/entries matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 3 key requests
          cat > expected << EOF
            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete

            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete

            Type: enrollment
            Status: complete
          EOF

          diff expected actual

      - name: Check keys after enrollment
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/key(s) matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 2 keys
          # NOTE: EC key size is -1
          cat > expected << EOF
            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-CRMFPopClient-without-POP

            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-CRMFPopClient-with-POP

            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-PKI-CLI-without-POP
          EOF

          diff expected actual

      - name: Check key record after enrollment
        run: |
          docker exec pki pki \
              -u kraadmin \
              -w Secret.123 \
              kra-key-find \
              --owner UID=test-PKI-CLI-without-POP \
              | tee output

          KEY_ID=$(sed -n "s/^\s*Key ID:\s*\(\S*\)$/\1/p" output)
          echo "Key ID: $KEY_ID"
          echo $KEY_ID > cert.key_id

          DEC_KEY_ID=$(python -c "print(int('$KEY_ID', 16))")
          echo "Dec Key ID: $DEC_KEY_ID"

          # get key record
          docker exec pki ldapsearch \
              -H ldap://ds.example.com:3389 \
              -x \
              -D "cn=Directory Manager" \
              -w Secret.123 \
              -b "cn=$DEC_KEY_ID,ou=keyRepository,ou=kra,dc=kra,dc=pki,dc=example,dc=com" \
              -o ldif_wrap=no \
              -LLL | tee output

          # normalize output
          sed \
              -e '/^$/d' \
              -e 's/^\(serialno\): .*$/\1: XXXXX/' \
              -e 's/^\(privateKeyData\):: .*$/\1:: XXXXX/' \
              -e 's/^\(publicKeyData\):: .*$/\1:: XXXXX/' \
              -e 's/^\(metaInfo: payloadEncryptionIV\):.*/\1:XXXXX/' \
              -e 's/^\(dateOfCreate\): .*$/\1: XXXXX/' \
              -e 's/^\(dateOfModify\): .*$/\1: XXXXX/' \
              output > actual

          cat > expected << EOF
          dn: cn=$DEC_KEY_ID,ou=keyRepository,ou=kra,dc=kra,dc=pki,dc=example,dc=com
          objectClass: top
          objectClass: keyRecord
          keyState: VALID
          serialno: XXXXX
          ownerName: UID=test-PKI-CLI-without-POP
          keySize: -1
          algorithm: 1.2.840.10045.2.1
          privateKeyData:: XXXXX
          publicKeyData:: XXXXX
          metaInfo: payloadEncrypted:false
          metaInfo: sessionKeyLength:128
          metaInfo: sessionKeyWrapAlgorithm:RSA
          metaInfo: sessionKeyKeyGenAlgorithm:AES
          metaInfo: payloadEncryptionOID:2.16.840.1.101.3.4.1.2
          metaInfo: payloadEncryptionIV:XXXXX
          metaInfo: payloadWrapAlgorithm:AES KeyWrap/Padding
          metaInfo: EllipticCurve:SECG elliptic curve secp521r1 (aka NIST P-521)
          metaInfo: sessionKeyType:AES
          dateOfCreate: XXXXX
          dateOfModify: XXXXX
          archivedBy: CA-pki.example.com-8443
          cn: $DEC_KEY_ID
          EOF

          diff expected actual

      - name: Recover cert key
        run: |
          KEY_ID=$(cat cert.key_id)
          echo "Key ID: $KEY_ID"

          # export cert into Base64-encoded format
          BASE64_CERT=$(docker exec pki pki nss-cert-export \
              --format DER \
              test-PKI-CLI-without-POP \
              | base64 --wrap=0)
          echo "Cert: $BASE64_CERT"

          # create retrieval request with key ID, cert, and passphrase
          cat > request.json <<EOF
          {
            "ClassName" : "com.netscape.certsrv.key.KeyRecoveryRequest",
            "Attributes" : {
              "Attribute" : [ {
                "name" : "keyId",
                "value" : "$KEY_ID"
              }, {
                "name" : "certificate",
                "value" : "$BASE64_CERT"
              }, {
                "name" : "passphrase",
                "value" : "Secret.123"
              } ]
            }
          }
          EOF

          # retrieve archived cert and key into PKCS #12 file
          # https://github.com/dogtagpki/pki/wiki/Retrieving-Archived-Key
          docker exec pki pki \
              --debug \
              -n caadmin \
              kra-key-retrieve \
              --input $SHARED/request.json \
              --transport kra_transport \
              --output-data test-PKI-CLI-without-POP.p12

          # import PKCS #12 file into NSS database with the passphrase
          docker exec pki pki \
              --debug \
              -d nssdb \
              pkcs12-import \
              --pkcs12 test-PKI-CLI-without-POP.p12 \
              --password Secret.123

          # remove archived cert from NSS database
          docker exec pki pki -d nssdb nss-cert-del UID=test-PKI-CLI-without-POP

          # import original cert into NSS database
          docker exec pki pki \
              --debug \
              -d nssdb \
              nss-cert-import \
              --cert test-PKI-CLI-without-POP.crt \
              test-PKI-CLI-without-POP

          docker exec pki pki \
              --debug \
              -d nssdb nss-cert-show test-PKI-CLI-without-POP | tee output

          # normalize output
          sed \
              -e '/^ *Serial Number:/d' \
              -e '/^ *Not Valid Before:/d' \
              -e '/^ *Not Valid After:/d' \
              output > actual

          # the cert should match the key (trust flags must be u,u,u)
          cat > expected << EOF
            Nickname: test-PKI-CLI-without-POP
            Subject DN: UID=test-PKI-CLI-without-POP
            Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
            Trust Flags: u,u,u
          EOF

          diff expected actual

      - name: Check key requests after recovery
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-request-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/entries matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 4 key requests
          cat > expected << EOF
            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete

            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete

            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete
          EOF

          diff expected actual

      - name: Check keys after recovery
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/key(s) matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 4 keys
          # NOTE: test-CRMFPopClient-with-POP and test-PKI-CLI-without-POP keys don't have a status
          cat > expected << EOF
            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-CRMFPopClient-without-POP

            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-CRMFPopClient-with-POP

            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-PKI-CLI-without-POP
          EOF

          diff expected actual

      - name: Enroll EC cert using PKI CLI with POP
        run: |
          # generate key and cert request
          # https://github.com/dogtagpki/pki/wiki/Generating-Certificate-Request-with-PKI-NSS
          docker exec pki pki nss-cert-request \
              --key-type EC \
              --curve nistp521 \
              --type crmf \
              --pop \
              --subject UID=test-PKI-CLI-with-POP \
              --transport kra_transport \
              --csr test-PKI-CLI-with-POP.csr

          docker exec pki cat test-PKI-CLI-with-POP.csr

          docker exec pki AtoB test-PKI-CLI-with-POP.csr test-PKI-CLI-with-POP.der
          docker exec pki dumpasn1 test-PKI-CLI-with-POP.der

          # issue cert
          # https://github.com/dogtagpki/pki/wiki/Issuing-Certificates
          docker exec pki pki \
              -u caadmin \
              -w Secret.123 \
              ca-cert-issue \
              --request-type crmf \
              --profile caECUserCert \
              --subject UID=test-PKI-CLI-with-POP \
              --csr-file test-PKI-CLI-with-POP.csr \
              --output-file test-PKI-CLI-with-POP.crt

          # import cert into NSS database
          docker exec pki pki nss-cert-import --cert test-PKI-CLI-with-POP.crt test-PKI-CLI-with-POP
          docker exec pki pki nss-cert-show test-PKI-CLI-with-POP | tee output

          # normalize output
          sed \
              -e '/^ *Serial Number:/d' \
              -e '/^ *Not Valid Before:/d' \
              -e '/^ *Not Valid After:/d' \
              output > actual

          # the cert should match the key (trust flags must be u,u,u)
          cat > expected << EOF
            Nickname: test-PKI-CLI-with-POP
            Subject DN: UID=test-PKI-CLI-with-POP
            Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
            Trust Flags: u,u,u
          EOF

          diff expected actual

      - name: Check key requests after enrollment
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-request-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/entries matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 3 key requests
          cat > expected << EOF
            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete

            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete

            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete

            Type: enrollment
            Status: complete
          EOF

          diff expected actual

      - name: Check keys after enrollment
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/key(s) matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 2 keys
          # NOTE: EC key size is -1
          cat > expected << EOF
            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-CRMFPopClient-without-POP

            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-CRMFPopClient-with-POP

            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-PKI-CLI-without-POP

            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-PKI-CLI-with-POP
          EOF

          diff expected actual

      - name: Check key record after enrollment
        run: |
          docker exec pki pki \
              -u kraadmin \
              -w Secret.123 \
              kra-key-find \
              --owner UID=test-PKI-CLI-with-POP \
              | tee output

          KEY_ID=$(sed -n "s/^\s*Key ID:\s*\(\S*\)$/\1/p" output)
          echo "Key ID: $KEY_ID"
          echo $KEY_ID > cert.key_id

          DEC_KEY_ID=$(python -c "print(int('$KEY_ID', 16))")
          echo "Dec Key ID: $DEC_KEY_ID"

          # get key record
          docker exec pki ldapsearch \
              -H ldap://ds.example.com:3389 \
              -x \
              -D "cn=Directory Manager" \
              -w Secret.123 \
              -b "cn=$DEC_KEY_ID,ou=keyRepository,ou=kra,dc=kra,dc=pki,dc=example,dc=com" \
              -o ldif_wrap=no \
              -LLL | tee output

          # normalize output
          sed \
              -e '/^$/d' \
              -e 's/^\(serialno\): .*$/\1: XXXXX/' \
              -e 's/^\(privateKeyData\):: .*$/\1:: XXXXX/' \
              -e 's/^\(publicKeyData\):: .*$/\1:: XXXXX/' \
              -e 's/^\(metaInfo: payloadEncryptionIV\):.*/\1:XXXXX/' \
              -e 's/^\(dateOfCreate\): .*$/\1: XXXXX/' \
              -e 's/^\(dateOfModify\): .*$/\1: XXXXX/' \
              output > actual

          cat > expected << EOF
          dn: cn=$DEC_KEY_ID,ou=keyRepository,ou=kra,dc=kra,dc=pki,dc=example,dc=com
          objectClass: top
          objectClass: keyRecord
          keyState: VALID
          serialno: XXXXX
          ownerName: UID=test-PKI-CLI-with-POP
          keySize: -1
          algorithm: 1.2.840.10045.2.1
          privateKeyData:: XXXXX
          publicKeyData:: XXXXX
          metaInfo: payloadEncrypted:false
          metaInfo: sessionKeyLength:128
          metaInfo: sessionKeyWrapAlgorithm:RSA
          metaInfo: sessionKeyKeyGenAlgorithm:AES
          metaInfo: payloadEncryptionOID:2.16.840.1.101.3.4.1.2
          metaInfo: payloadEncryptionIV:XXXXX
          metaInfo: payloadWrapAlgorithm:AES KeyWrap/Padding
          metaInfo: EllipticCurve:SECG elliptic curve secp521r1 (aka NIST P-521)
          metaInfo: sessionKeyType:AES
          dateOfCreate: XXXXX
          dateOfModify: XXXXX
          archivedBy: CA-pki.example.com-8443
          cn: $DEC_KEY_ID
          EOF

          diff expected actual

      - name: Recover cert key
        run: |
          KEY_ID=$(cat cert.key_id)
          echo "Key ID: $KEY_ID"

          # export cert into Base64-encoded format
          BASE64_CERT=$(docker exec pki pki nss-cert-export \
              --format DER \
              test-PKI-CLI-with-POP \
              | base64 --wrap=0)
          echo "Cert: $BASE64_CERT"

          # create retrieval request with key ID, cert, and passphrase
          cat > request.json <<EOF
          {
            "ClassName" : "com.netscape.certsrv.key.KeyRecoveryRequest",
            "Attributes" : {
              "Attribute" : [ {
                "name" : "keyId",
                "value" : "$KEY_ID"
              }, {
                "name" : "certificate",
                "value" : "$BASE64_CERT"
              }, {
                "name" : "passphrase",
                "value" : "Secret.123"
              } ]
            }
          }
          EOF

          # retrieve archived cert and key into PKCS #12 file
          # https://github.com/dogtagpki/pki/wiki/Retrieving-Archived-Key
          docker exec pki pki \
              -n caadmin \
              kra-key-retrieve \
              --input $SHARED/request.json \
              --transport kra_transport \
              --output-data test-PKI-CLI-with-POP.p12

          # import PKCS #12 file into NSS database with the passphrase
          docker exec pki pki \
              -d nssdb \
              pkcs12-import \
              --pkcs12 test-PKI-CLI-with-POP.p12 \
              --password Secret.123

          # remove archived cert from NSS database
          docker exec pki pki -d nssdb nss-cert-del UID=test-PKI-CLI-with-POP

          # import original cert into NSS database
          docker exec pki pki -d nssdb nss-cert-import \
              --cert test-PKI-CLI-with-POP.crt \
              test-PKI-CLI-with-POP

          docker exec pki pki -d nssdb nss-cert-show test-PKI-CLI-with-POP | tee output

          # normalize output
          sed \
              -e '/^ *Serial Number:/d' \
              -e '/^ *Not Valid Before:/d' \
              -e '/^ *Not Valid After:/d' \
              output > actual

          # the cert should match the key (trust flags must be u,u,u)
          cat > expected << EOF
            Nickname: test-PKI-CLI-with-POP
            Subject DN: UID=test-PKI-CLI-with-POP
            Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
            Trust Flags: u,u,u
          EOF

          diff expected actual

      - name: Check key requests after recovery
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-request-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/entries matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 4 key requests
          cat > expected << EOF
            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete

            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete

            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete

            Type: enrollment
            Status: complete

            Type: recovery
            Status: complete
          EOF

          diff expected actual

      - name: Check keys after recovery
        run: |
          docker exec pki pki \
              -n caadmin \
              kra-key-find \
              | tee output

          # normalize output
          sed \
              -e '/-----/d' \
              -e '/key(s) matched/d' \
              -e '/Number of entries returned/d' \
              -e '/^ *Request ID:/d' \
              -e '/^ *Key ID:/d' \
              -e '/^ *Creation Time:/d' \
              -e '/^ *Modification Time:/d' \
              output > actual

          # there should be 4 keys
          # NOTE: test-CRMFPopClient-with-POP and test-PKI-CLI-with-POP keys don't have a status
          cat > expected << EOF
            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-CRMFPopClient-without-POP

            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-CRMFPopClient-with-POP

            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-PKI-CLI-without-POP

            Algorithm: 1.2.840.10045.2.1
            Size: -1
            Owner: UID=test-PKI-CLI-with-POP
          EOF

          diff expected actual

      - name: Remove KRA
        run: docker exec pki pkidestroy -s KRA -v

      - name: Remove CA
        run: docker exec pki pkidestroy -s CA -v

      - name: Check PKI server systemd journal
        if: always()
        run: |
          docker exec pki journalctl -x --no-pager -u pki-tomcatd@pki-tomcat.service

      - name: Check PKI server access log
        if: always()
        run: |
          docker exec pki find /var/log/pki/pki-tomcat -name "localhost_access_log.*" -exec cat {} \;

      - name: Check CA debug log
        if: always()
        run: |
          docker exec pki find /var/lib/pki/pki-tomcat/logs/ca -name "debug.*" -exec cat {} \;

      - name: Check KRA debug log
        if: always()
        run: |
          docker exec pki find /var/lib/pki/pki-tomcat/logs/kra -name "debug.*" -exec cat {} \;
