name: Ollama

on: workflow_call

env:
  DS_IMAGE: ${{ vars.DS_IMAGE || 'quay.io/389ds/dirsrv' }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      #- name: Install Ollama
      #  run: curl -fsSL https://ollama.com/install.sh | sh

      #- name: Check Ollama
      #  run: ollama list

      #- name: Run llama3.2
      #  run: ollama run llama3.2

      - name: Run Ollama container
        run: |
          docker run \
              -d \
              -v ollama:/root/.ollama \
              -p 11434:11434 \
              --name ollama \
              ollama/ollama

      - name: Run llama3.2
        run: |
          docker exec ollama ollama run llama3

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Retrieve PKI images
        uses: actions/cache@v4
        with:
          key: pki-images-${{ github.sha }}
          path: pki-images.tar

      - name: Load PKI images
        run: docker load --input pki-images.tar

      - name: Set up runner container
        run: |
          tests/bin/runner-init.sh \
              --hostname=pki.example.com \
              pki
