name: Python Tests

on: [push, pull_request]

jobs:
  build:
    name: Waiting for build
    uses: ./.github/workflows/wait-for-build.yml
    secrets: inherit

  python-lint-test:
    name: Python lint
    needs: build
    uses: ./.github/workflows/python-lint-test.yml
