name: Server memory leak test

on: workflow_call

env:
  DS_IMAGE: ${{ vars.DS_IMAGE || 'quay.io/389ds/dirsrv' }}

jobs:
  # docs/installation/ca/Installing_CA.md
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Retrieve PKI images
        uses: actions/cache@v5
        with:
          key: pki-images-${{ github.sha }}
          path: pki-images.tar

      - name: Load PKI images
        run: docker load --input pki-images.tar

      - name: Create network
        run: docker network create example

      - name: Set up PKI container
        run: |
          tests/bin/runner-init.sh \
              --hostname=pki.example.com \
              --network=example \
              --network-alias=pki.example.com \
              pki

          docker exec pki rpm -qa | grep openjdk
          docker exec pki dnf install -y java-25-openjdk-devel

      - name: Create PKI server
        run: |
          docker exec pki pki-server create -v
          docker exec pki pki-server nss-create --no-password

      - name: Create CA signing cert
        run: |
          docker exec pki pki-server cert-request \
              --subject "CN=CA Signing Certificate" \
              --ext /usr/share/pki/server/certs/ca_signing.conf \
              ca_signing

          docker exec pki pki-server cert-create \
              --ext /usr/share/pki/server/certs/ca_signing.conf \
              ca_signing

          docker exec pki pki-server cert-import ca_signing

      - name: Create SSL server cert
        run: |
          docker exec pki pki-server cert-request \
              --subject "CN=pki.example.com" \
              --ext /usr/share/pki/server/certs/sslserver.conf \
              sslserver

          docker exec pki pki-server cert-create \
              --issuer ca_signing \
              --ext /usr/share/pki/server/certs/sslserver.conf \
              sslserver

          docker exec pki pki-server cert-import sslserver

      - name: Create HTTPS connector
        run: |
          docker exec pki pki-server jss-enable

          docker exec pki pki-server http-connector-add \
              --port 8443 \
              --scheme https \
              --secure true \
              --sslEnabled true \
              --sslProtocol SSL \
              --sslImpl org.dogtagpki.jss.tomcat.JSSImplementation \
              Secure

          docker exec pki pki-server http-connector-cert-add \
              --keyAlias sslserver \
              --keystoreType pkcs11 \
              --keystoreProvider Mozilla-JSS

      - name: Deploy webapps
        run: |
          docker exec pki pki-server webapp-deploy \
              --descriptor /usr/share/pki/server/conf/Catalina/localhost/ROOT.xml \
              ROOT

          docker exec pki pki-server webapp-deploy \
              --descriptor /usr/share/pki/server/conf/Catalina/localhost/pki.xml \
              pki

      - name: Start PKI server
        run: |
          docker exec pki pki-server start

          PID=$(docker exec pki ps -C java -o pid --no-headers | awk '{print $1;}')
          echo "PID=$PID"
          echo "$PID" > java.pid

      - name: Initialize PKI client
        run: |
          docker exec pki pki nss-cert-import \
              --cert /var/lib/pki/pki-tomcat/conf/certs/ca_signing.crt \
              --trust CT,C,C \
              ca_signing

      - name: Check initial heap
        run: |
          PID=$(cat java.pid)

          # run garbage collector
          docker exec pki jcmd $PID GC.run
          sleep 5

          # get object class names and counts
          docker exec pki jhsdb jmap --histo --pid $PID \
              | tail -n +9 \
              | grep -E 'org.dogtagpki|org.mozilla' \
              | awk '{print $4, $2}' \
              | sort \
              | tee heap1

      - name: Idle for 1 minute
        run: |
          sleep 60

      - name: Check heap after idle
        run: |
          PID=$(cat java.pid)

          # run garbage collector
          docker exec pki jcmd $PID GC.run
          sleep 5

          # get object class names and counts
          docker exec pki jhsdb jmap --histo --pid $PID \
              | tail -n +9 \
              | grep -E 'org.dogtagpki|org.mozilla' \
              | awk '{print $4, $2}' \
              | sort \
              | tee heap2

      - name: Check memory leak after idle
        run: |
          tests/bin/check-memory-leak.py heap1 heap2

          # if the object count increased it's likely that
          # the object was not released properly for garbage
          # collection which causes a memory leak

          # TODO: test should fail if there's a memory leak

      - name: Run load test with HTTP
        run: |
          PID=$(cat java.pid)

          # run pki info command 50 times
          for i in $(seq 1 50); do
              docker exec pki pki -U http://pki.example.com:8080 info
          done

      - name: Check heap after load test with HTTP
        run: |
          PID=$(cat java.pid)

          # run garbage collector
          docker exec pki jcmd $PID GC.run
          sleep 5

          # get object class names and counts
          docker exec pki jhsdb jmap --histo --pid $PID \
              | tail -n +9 \
              | grep -E 'org.dogtagpki|org.mozilla' \
              | awk '{print $4, $2}' \
              | sort \
              | tee heap3

      - name: Check memory leak after load test with HTTP
        run: |
          tests/bin/check-memory-leak.py heap2 heap3

          # if the object count increased by 50 times (i.e. matching
          # the load test) it's likely that the object was not released
          # properly for garbage collection which causes a memory leak

          # TODO: test should fail if there's a memory leak

      - name: Run load test with HTTPS
        run: |
          PID=$(cat java.pid)

          # run pki info command 50 times
          for i in $(seq 1 50); do
              docker exec pki pki info
          done

      - name: Check heap after load test with HTTPS
        run: |
          PID=$(cat java.pid)

          # run garbage collector
          docker exec pki jcmd $PID GC.run
          sleep 5

          # get object class names and counts
          docker exec pki jhsdb jmap --histo --pid $PID \
              | tail -n +9 \
              | grep -E 'org.dogtagpki|org.mozilla' \
              | awk '{print $4, $2}' \
              | sort \
              | tee heap4

      - name: Check memory leak after load test with HTTPS
        run: |
          tests/bin/check-memory-leak.py heap3 heap4

          # if the object count increased by 50 times (i.e. matching
          # the load test) it's likely that the object was not released
          # properly for garbage collection which causes a memory leak

          # TODO: test should fail if there's a memory leak

      - name: Stop PKI server
        run: |
          docker exec pki pki-server stop --wait -v

      - name: Remove PKI server
        run: |
          docker exec pki pki-server remove -v

      - name: Check PKI server systemd journal
        if: always()
        run: |
          docker exec pki journalctl -x --no-pager -u pki-tomcatd@pki-tomcat.service

      - name: Check PKI server access log
        if: always()
        run: |
          docker exec pki find /var/log/pki/pki-tomcat -name "localhost_access_log.*" -exec cat {} \;
